appendix_a = {
    "actual_range": {"Type": "N", "Use": ["C", "D", "BO"]},
    "add_offset": {"Type": "N", "Use": ["C", "D", "BO"]},
    "ancillary_variables": {"Type": "S", "Use": ["D"]},
    "axis": {"Type": "S", "Use": ["C", "BI"]},
    "bounds": {"Type": "S", "Use": ["C"]},
    "calendar": {"Type": "S", "Use": ["C", "BI"]},
    "cell_measures": {"Type": "S", "Use": ["D", "Do"]},
    "cell_methods": {"Type": "S", "Use": ["D"]},
    "cf_role": {"Type": "S", "Use": ["C", "BI"]},
    "climatology": {"Type": "S", "Use": ["C"]},
    "comment": {"Type": "S", "Use": ["G", "C", "D"]},
    "compress": {"Type": "S", "Use": ["C"]},
    "computed_standard_name": {"Type": "S", "Use": ["C", "BI"]},
    "Conventions": {"Type": "S", "Use": ["G"]},
    "coordinate_interpolation": {"Type": "S", "Use": ["D", "Do"]},
    "coordinates": {"Type": "S", "Use": ["D", "M", "Do"]},
    "dimensions": {"Type": "S", "Use": ["Do"]},
    "external_variables": {"Type": "S", "Use": ["G"]},
    "_FillValue": {"Type": "D", "Use": ["C", "D", "BO"]},
    "featureType": {"Type": "S", "Use": ["G"]},
    "flag_masks": {"Type": "D", "Use": ["D"]},
    "flag_meanings": {"Type": "S", "Use": ["D"]},
    "flag_values": {"Type": "D", "Use": ["D"]},
    "formula_terms": {"Type": "S", "Use": ["C", "BO"]},
    "geometry": {"Type": "S", "Use": ["C", "D", "Do"]},
    "geometry_type": {"Type": "S", "Use": ["M"]},
    "grid_mapping": {"Type": "S", "Use": ["D", "M", "Do"]},
    "history": {"Type": "S", "Use": ["G", "Gr"]},
    "instance_dimension": {"Type": "S", "Use": []},
    "institution": {"Type": "S", "Use": ["G", "D"]},
    "interior_ring": {"Type": "S", "Use": ["M"]},
    "leap_month": {"Type": "N", "Use": ["C", "BI"]},
    "leap_year": {"Type": "N", "Use": ["C", "BI"]},
    "location": {"Type": "S", "Use": ["D", "Do"]},
    "location_index_set": {"Type": "S", "Use": ["D", "Do"]},
    "long_name": {"Type": "S", "Use": ["C", "D", "Do", "BI"]},
    "mesh": {"Type": "S", "Use": ["D", "Do"]},
    "missing_value": {"Type": "D", "Use": ["C", "D", "BO"]},
    "month_lengths": {"Type": "N", "Use": ["C", "BI"]},
    "node_coordinates": {"Type": "S", "Use": ["M"]},
    "node_count": {"Type": "S", "Use": ["M"]},
    "nodes": {"Type": "S", "Use": ["C"]},
    "part_node_count": {"Type": "S", "Use": ["M"]},
    "positive": {"Type": "S", "Use": ["C", "BI"]},
    "references": {"Type": "S", "Use": ["G", "D"]},
    "sample_dimension": {"Type": "S", "Use": []},
    "scale_factor": {"Type": "N", "Use": ["C", "D", "BO"]},
    "source": {"Type": "S", "Use": ["G", "D"]},
    "standard_error_multiplier": {"Type": "N", "Use": ["D"]},
    "standard_name": {"Type": "S", "Use": ["C", "D", "BI"]},
    "title": {"Type": "S", "Use": ["G", "Gr"]},
    "units": {"Type": "S", "Use": ["C", "D", "BI"]},
    "units_metadata": {"Type": "S", "Use": ["C", "D", "BI"]},
    "valid_max": {"Type": "N", "Use": ["C", "D", "BO"]},
    "valid_min": {"Type": "N", "Use": ["C", "D", "BO"]},
    "valid_range": {"Type": "N", "Use": ["C", "D", "BO"]},
}
