name: UGRID Plugin Tests

on:
  pull_request:
  push:
    branches: [master,develop,main]

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Setup Micromamba
      uses: mamba-org/provision-with-micromamba@main
      with:
        environment-file: false

    - name: Python
      shell: bash -l {0}
      run: |
        micromamba create --name TEST python=3 pip --file requirements.txt --file test_requirements.txt --channel conda-forge
        micromamba activate TEST
        pip install -e . --no-deps --force-reinstall

    - name: micromamba Info
      shell: bash -l {0}
      run: |
        micromamba activate TEST
        micromamba info --all
        micromamba list

    - name: cc-plugin-glider tests
      shell: bash -l {0}
      run: |
        micromamba activate TEST
        git clone https://github.com/ioos/cc-checker-ugrid.git
        cd cc-checker-ugrid
        pip install -e . --no-deps --force-reinstall
        micromamba install --file requirements.txt --file requirements-dev.txt
        pytest -s -rxs -v cc_plugin_ugrid
