name: UGRID Plugin Tests

on:
  pull_request:
  push:
    branches: [master, develop]

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Install necessary Python packages
      uses: ./.github/actions/python-package-setup
      with:
        python-version: {{ matrix.python-version }}

    - name: cc-plugin-glider tests
      shell: bash -l {0}
      run: |
        source activate TEST
        git clone https://github.com/ioos/cc-checker-ugrid.git
        cd cc-checker-ugrid
        pip install -e . --no-deps --force-reinstall
        conda install --file requirements.txt --file requirements-dev.txt ;
        pytest -s -rxs -v cc_plugin_ugrid
