name: OG Plugin Tests

on:
  pull_request:
  push:

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Setup Micromamba
      uses: mamba-org/setup-micromamba@v2
      with:
        environment-name: TEST
        init-shell: bash
        create-args: >-
          python=3 pip
          --file requirements.txt
          --file test_requirements.txt
          --channel conda-forge

    - name: Install compliance-checker
      shell: bash -l {0}
      run: |
        python -m pip install -e . --no-deps --force-reinstall

    - name: cc-plugin-og tests
      shell: bash -l {0}
      run: >
        git clone https://github.com/uw-farlab/cc-plugin-og.git
        && cd cc-plugin-og
        && micromamba install --file requirements.txt --channel conda-forge
        && micromamba remove compliance-checker --no-prune --force
        && python -m pip install -e . --no-deps --force-reinstall
        && python -m pytest -s -rxs -v cc_plugin_og
