name: OG Plugin Tests

on:
  pull_request:
  push:

jobs:
  run:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -l {0}

    steps:
    - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8  # v5.0.0
      with:
        persist-credentials: false

    - name: Setup Micromamba
      uses: mamba-org/setup-micromamba@add3a49764cedee8ee24e82dfde87f5bc2914462 # v2.0.7
      with:
        environment-name: TEST
        init-shell: bash
        create-args: >-
          python=3 pip
          --file test_requirements.txt
          --channel conda-forge

    - name: Install compliance-checker
      run: |
        python -m pip install -e . --no-deps --force-reinstall

    - name: cc-plugin-og tests
      run: >
        git clone https://github.com/uw-farlab/cc-plugin-og.git
        && cd cc-plugin-og
        && micromamba install --file requirements.txt --channel conda-forge
        && micromamba remove compliance-checker --no-prune-deps --force
        && python -m pip install -e . --no-deps --force-reinstall
        && python -m pytest -s -rxs -v cc_plugin_og
    permissions:
      actions: none
