name: Full Tests (Integration)

on:
  pull_request:
  push:

# Deny all permissions by default
permissions: {}

jobs:
  run:
    name: WASM=${{ matrix.emscripten }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        emscripten: [ false ]
        include:
          - emscripten: true
      fail-fast: false
    defaults:
      run:
        shell: bash -l {0}

    steps:
    - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1  # v7.0.1
      with:
        persist-credentials: false

    - name: Setup Micromamba ${{ matrix.python-version }}
      uses: mamba-org/setup-micromamba@f457c30a868e4760d3a6fcea5f25dc655b8edf39 # v3.2.1
      with:
        environment-name: TEST
        init-shell: bash
        create-args: >-
          python=3 toml --channel conda-forge

    - name: Install compliance-checker
      # Revert to wheels only when we have an ncgen alternative.
      run: |
        python install_from_toml.py
        python -m pip install -e . --no-deps --force-reinstall

    - name: Test with cf-units (optional)
      if: matrix.emscripten == true
      run: >
        micromamba remove cf-units --force
        && micromamba install pyudunits2
        && micromamba install pydap

    - name: Integration Tests
      run: python -m pytest -s -rxs -v --vcr-record=none compliance_checker
